### PR TITLE
UP-4722: Adding some pags

### PR DESCRIPTION
**Pull request by jgribonvald**
https://issues.jasig.org/browse/UP-4722

These pags are used in our context. For details see each commits.

Unit test are provided.

### CODE REVIEW

**Comment by jgribonvald** [comment]
For the last commit I can't provide a test case as I don't know you we can mock the applicationContext needed in class (their is a code blocker to avoid to load applicationContext in test mode) If you tell me how to do i can make it ;)

**Comment by bjagg** [comment]
These additions look great! The only quibble is the import order. See https://wiki.jasig.org/display/UPM42/JetBrains+IntelliJ on correcting it.

**Comment by jgribonvald** [comment]
Ok, so 
updated for import order 
adapted from IntegerTester to AbstractIntegerTester rebuild
and tested with unit test

tell me if something remaining

**Comment by drewwills** [comment]
@jgribonvald,

Thanks for staying on top of this item.

> tell me if something remains

I'm going to take care of it (in just a minute), but please open a JIRA ticket for Pull Requests (in most cases) and provide a link in the summary.

**Comment by jgribonvald** [comment]
Ho sorry ! I will do it so for others tomorrow.

**Comment by drewwills** [comment]
Merged out-of-band.

**Pull request closed without merging**
