### PR TITLE
UP- 4697 Enhancement (epic) of the Off canvas

### PR DESCRIPTION
**Pull request by cousquer**
[https://issues.jasig.org/browse/UP-4697](url)
to test don't forget to switch : \<xsl:param name="USE_FLYOUT_MENUS" select="'true'" /> in navigation.xsl

UP-4697 is trying to fix several existing Jiras to give me a branch name...
UP-4622 Add offcanvas stickynav flyout : there is a bug with the optional fly-out menu on iPhone
UP-4670 An horizontal scrollbar appears on narrow display (new mobile nav)
UP-4671 the new mobile nav doesn't have the right background-color (improvement: new LESS variable to handle colors and position in variable.less)
UP-4707 Desktop Nav is missing in IE 11 and previous version
UP-4708 IE 11 and previous browsers: The space created for the "responsive left nav" does not disappear when desktop users change window size if the menu is open
No-Jira Implement a new animated pure CSS Hambuger menu on mobile
No-Jira Use GPU accelerated CSS properties to animate the offcanvas
No-Jira Add support for the offcanvas to ie9, ie10, ie 11
No-Jira Improve uPortal Accessibility, a blind people can navigate, open/close main Navigation, open/close optional subNav (aka optional fly-out menus) and reach directly one portlet in maximize view located into Xth tab of the main Navigation with Voiceover (see https://t.co/1UdCIlfLKY). Improvement on keyboard navigation (tab/enter/space)
No-jira Enhancement of the Touch Area of the sub nav toggle, tabs gripper and tabs delete buttons for Touch devices
No-jira The bootstrap's Font (glyphicons) wasn't update with the last uPortal Bootstrap update : some Bootstrap css classes don't work correctly because glyphicons font wasn't bump to the right version + add font in Wolff2 + security Fix on the fonts.
partly (99%) resolve UP-4695 for breackpoints :765px, 766px 767px, breackpoint 769px, 770px, .... Still a display problem at 768px tue to two differents breackpoints in Bootstrap respondr. but it's usable in 768px now.
Tested on Windows 1O, OSX, Linux on Chrome / FF / Edge /Safari / IE11 / IE10 / IE 9
IOS latest (Iphone 6S / 5 /4) [chrome /safari] / IOS Old (old IPAD 1 not updated) (old chrome / old Safari) / Android
with and without the fly-out enable.

### CODE REVIEW

**Comment by jgribonvald** [comment]
:+1:

**Comment by ITassas** [comment]
:+1:

**Comment by drewwills** [comment]
Thanks @cousquer!

**Comment by cousquer** [comment]
@drewwills if you need clarification on some points of this pull-request. Feel free to ping me in the comments.
I had to make some choices to stabilize the all possibilities (with / without fly-out menu, mobile / desktop, Nameable,breakpoint's problems on iPad , LESS cascading limitation, etc.)
and, please, correct all my misspellings ... :-)

**Comment by jgribonvald** [comment]
It would be great to have comments with // that are less comments instead of /* */ that are for css comments. 
Is it possible ?

Else a big :+1:  I already adopted it in our dev version ;)

**Comment by drewwills** [comment]
From an email on uportal-user:

> This pull request solved our problem. The menu is much better and it seems to be working on all devices I have tested. 
> 
> I have only tested this for a few hours yesterday. It took some time to implement this into our customized version of uPortal 4.3, but it was working great. I will make a merge request on Monday (on OU's gitlab), so Aaron will be able to take a look at it then.
> 
> All version of software on iOS were up to date. 
> iOS version: 9.3.2
> iOS Chrome version: 51.0.2704.104
> iOS Firefox version: 4.0
> 
> I also noticed this was happening on OSX with the latest version of El Capitan. This issue was happening on Safari, but not the latest version of Chrome. Chrome was working fine on OSX, but not iOS. However, this pull request fixed this issue on as OSX as well. It is working on all devices I have tested. 
> 
> More testing to be done on Monday.
> 
>

**Comment by drewwills** [comment]
That's interesting @jgribonvald -- I didn't realize that LESS supports //-style comments (iirc CSS doesn't).

**Comment by cousquer** [comment]
@drewwills @jgribonvald [http://lesscss.org/features/#features-overview-feature-comments](url) ;-)

**Comment by cousquer** [comment]
@ChristianMurphy Do-you think that what you have done with #722 (adapted from #722) can be done with #681 on Jasig:rel-4-3-patches ?
I cc @bjagg and @drewwills.

**Comment by ChristianMurphy** [comment]
The pull request to master (#723) includes the changes from this pull request (#681), so that is already done.
As far as backporting the changes from this PR (#681) to rel-4-3-patches, it should be doable.
[`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) is what I used to make #722 and #723, it should work for backporting these changes as well.

**Comment by cousquer** [comment]
@ChristianMurphy @drewwills I've cherry-pick #681 into rel-4-3-patches with this PR [https://github.com/Jasig/uPortal/pull/734](https://github.com/Jasig/uPortal/pull/734)
it was doable :-)

**Pull request merged**
