### PR TITLE
UP-4432:  Switch the default PAGS implementation from XML file config to...

### PR DESCRIPTION
**Pull request by drewwills**
... the database (JPA entity) flavor;  @depricate the legacy version

https://issues.jasig.org/browse/UP-4432

### CODE REVIEW

**Comment by jameswennmacher** [comment]
I suggest also increasing maxActive in uPortal's databaseContext.xml file from 75 to 100.  I don't think we really need a 25 increase just due to this feature, but from load tests I've seen the 75 value is a little small so I think going to 100 as a default is not unreasonable at all.

**Comment by jameswennmacher** [comment]
+1

**Comment by drewwills** [comment]
@jameswennmacher -- done.

**Comment by drewwills** [comment]
12 days on the queue -- time to merge.

**Pull request merged**
