### PR TITLE
UP-4426: Upgrading Portal Bootstrap to v3.3.5

### PR DESCRIPTION
**Pull request by doodelicious**
https://issues.jasig.org/browse/UP-4426

Upgraded Portal Bootstrap to v.3.3.5:

https://github.com/twbs/bootstrap/releases/tag/v3.3.5

### CODE REVIEW

**Comment by drewwills** [comment]
This PR was checked and merged out-of-band -- thanks @doodelicious!

**Comment by jgribonvald** [comment]
Is there a reason why this version wasn't updated in respondr theme in branch rel-4.2-patches whereas it's on master ? Test are needed ? Or a feedback of use ?

**Comment by jameswennmacher** [comment]
We generally try to put important functional changes in a prior release, but updates and new functionality in master.  It reduces the load on testing, etc. since there are limited resources.  You can always include this into your 4.2 version.  I will say though that 4.3 has some significant improvements especially in performance that make it more compelling than 4.2.x at this point and both will be released very soon.

**Comment by jgribonvald** [comment]
Thanks James !

I will watch on 4.3 also, i didn't have overview on 4.3 state.

**Pull request closed without merging**
