### PR TITLE
no-jira dragging and dropping of tabs and chromes does not work due t…

### PR DESCRIPTION
**Pull request by MichaelVose2**
Hello. 

When uPortal was upgraded it seems 2 css files utilised by the sluid skinning system were excluded. Unfortunatly these files controlled dragging and dropping for both tabs, and portlets - hence this pull request.

### CODE REVIEW

**Comment by cousquer** [comment]
@MichaelVose2 Be carefull you have pull this from your forks master branch. Please Follow the instruction of : 
https://wiki.jasig.org/display/UPC/Git+Workflow+for+Non-Committers
Can you also fill a Jira in https://issues.jasig.org with more details : uPortal version(s) affected by this bug, OS name and version, Browser's name and version.
because drag n drop of tabs and portlets works in the master branch...

**Comment by cousquer** [comment]
@MichaelVose2 since uPortal 4.3 the way of draging portlet has changed due to side effects while scrolling on mobile : go in portlet's options > Move this portlet, then a drag handle appears...
:-)

**Comment by MichaelVose2** [comment]
Hello,

Within Manchester we implemented uPortal 4.3 and dragging/dropping of tabs and portlets did not display properly due to these css files being missing. I will look at the vanilla version on my local vm tomorrow and see if the above changes are pertinent. If not, then I will need to update manchesters front end as we should not require the changes in this PR to make dragging/dropping work.

With regards to the incorrect usage of git -sorry - clearly this PR would need to be rejected anyhow.


________________________________

**Comment by cousquer** [comment]
@MichaelVose2  https://issues.jasig.org/browse/UP-4577

**Comment by drewwills** [comment]
I'm going to close this PR because it seems reasonably clear that we're not in a position to merge it.

Nevertheless, I very much appreciate the collaboration and dialog.  Please keep it up.

**Comment by cousquer** [comment]
@MichaelVose2 @drewwills Definitely yes.
The idea behind this pull request was really promising.
Perhaps the tone of my comment was rude, it was not my intention and it is only the fact that I am not a native English speaker (I'm French).
Again, it was very promising. Please keepit up

**Comment by MichaelVose2** [comment]
It is fine; what you stated was common sense, and clearly the changes you made could completely fix the issue I addressed in Manchester's implementation. We should only work on one PR which would change dragging and dropping, and your's seems to have made the most progress.
________________________________

**Pull request closed without merging**
