### PR TITLE
UP-4742: Use AlternativeMaximizedLink into sitemap - rel-4-3_patches

### PR DESCRIPTION
**Pull request by jgribonvald**
Set anchor url with Alternative Maximized Link on sitemap

Commit for branch rel-4-3_patches (see other PR for branch master)

### CODE REVIEW

**Comment by drewwills** [comment]
I'm 100% for the change, but is it a change we want to make in a patch release?

**Comment by jgribonvald** [comment]
This can follow up-4506, and it's advised !

After the sitemap should be rewrited as portlet (a TODO in xsl tell that)

**Comment by jgribonvald** [comment]
Could this be merged into 4.3 ? or you need something ?
Also there is the PR for the master ;)

**Comment by bjagg** [comment]
PR for master branch was merged.

The issue is semantic versioning where a patch release should only contain "fixes" while a minor release would contain enhancements. See http://semver.org/

**Comment by drewwills** [comment]
If the intent was already to use the Alternative Maximized Link in the sitemap -- and especially if there was a comment to that effect -- I'm cool with considering this a "bug fix" and merging.

**Comment by jgribonvald** [comment]
Sorry Drew I'm back to my work after long deserved hollidays and a good break.

Else yes it's needed if you use this parameter on navigation links, more if you don't have it in the sitemap the user won't understand if he uses the sitemap as navigation, ie when the channel is opened in an other way than in navigation.

Thanks

**Comment by drewwills** [comment]
A few additional observations...

- [] There appear to be some whitespace/indentation adjustments needed (element nesting levels changes, but existing elements weren't updated to reflect the changes)
- [] I think `<xsl:if>` is probably preferable over `<xsl:choose>` with an empty `<xsl:otherwise>`
- [] Anywhere we use `target="_blank"` we are also obligated to add `rel="noopener noreferrer"`

I'm going to update these items on this PR and merge.  I will also review the same things in `master`.

**Comment by drewwills** [comment]
Suggestions applied to both `rel-4-3-patches` and `master`;  merged out-of-band.

**Pull request closed without merging**
