### PR TITLE
feat: add web component polyfill to uPortal

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

Include a web component polyfill for all uPortal.
Avoids embedding a 100kb polyfill in every component on the page.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
:notebook: Started release of web components polyfill 2.0.4 is may not be completed before CI runs.

**Comment by ChristianMurphy** [comment]
selection_015

**Comment by drewwills** [comment]
I wish it wasn't needed, but this approach is probably the right way to handle this issue.  :+1:

**Comment by ChristianMurphy** [comment]
Full Firefox support is coming soon, and someday IE can be dropped, then this can be removed. :smile:

**Pull request merged**
