### PR TITLE
UP-4863: Change JGroups pbcast.GMS join_timeout to 2 seconds and max_…

### PR DESCRIPTION
**Pull request by bjagg**
…join_attempts to 3.

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

Reduce time spent joining JGroups cluster.

https://issues.jasig.org/browse/UP-4863

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
Are there any common/normal circumstances where we can expect joining to fail?

**Comment by bjagg** [comment]
Given a working, stable network, there should not be a need for 10 attempts to connect to the cluster.

**Comment by drewwills** [comment]
Do you know why it often fails (after 10 attempts) to connect on my local portal?

**Comment by bjagg** [comment]
It's attempting to connect to a cluster. In a dev environment, there usually isn't one.

I looked for a way to disable JGroups conditionally, but did not find much.

**Comment by drewwills** [comment]
How is a "cluster" defined in this context?  What's wrong with a cluster of one?

**Pull request merged**
