### PR TITLE
feat:  enhance the /api/v4-3/dlm/portletRegistry.json REST API, addin…

### PR DESCRIPTION
**Pull request by drewwills**
…g a field that indicates whether a portlet is a favorite

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

This PR adds a field to the JSON representing a portlet and produced by /api/v4-3/dlm/portletRegistry.json...

```
        {
            "fname": "reset-my-layout",
            "keywords": [
              
            ],
            "description": "Provides a means to reset your own layout to its default settings. Also deletes all portlet preference values.",
            "title": "Reset My Layout",
            "averageRating": 0,
            "name": "Reset My Layout",
            "ratingsCount": 0,
            "typeId": 2,
            "id": 26,
            "state": "PUBLISHED",
            "favorite": true,
            "parameters": {
              "iconUrl": {
                "name": "iconUrl",
                "description": "",
                "value": "\/ResourceServingWebapp\/rs\/tango\/0.8.90\/32x32\/categories\/applications-system.png"
              }
            }
          }
```

(HINT:  the `favorite` field is the new one.)

We are looking to use this API with the [esco-content-grid](https://github.com/uPortal-contrib/uPortal-web-components/blob/master/@uportal/esco-content-menu/README.md), which displays this information.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jgribonvald** [comment]
you need also to provide the maximized URL parameter and fallback to the generated portlet url, expect if you want the two parameters.

**Comment by drewwills** [comment]
@jgribonvald --

    you need also to provide the maximized URL parameter and fallback to the
    generated portlet url, expect if you want the two parameters.

Here's an example (of the JSON from this API) that has an `alternativeMaximizedLink`:

```
{
  "fname": "reset-my-layout",
  "keywords": [
    
  ],
  "description": "Provides a means to reset your own layout to its default settings. Also deletes all portlet preference values.",
  "title": "Reset My Layout",
  "averageRating": 0,
  "name": "Reset My Layout",
  "ratingsCount": 0,
  "typeId": 2,
  "id": 26,
  "state": "PUBLISHED",
  "favorite": true,
  "parameters": {
    "hideFromMobile": {
      "name": "hideFromMobile",
      "description": "",
      "value": "false"
    },
    "alternativeMaximizedLink": {
      "name": "alternativeMaximizedLink",
      "description": "",
      "value": "https:\/\/tikkido.com"
    },
    "blockImpersonation": {
      "name": "blockImpersonation",
      "description": "",
      "value": "false"
    },
    "iconUrl": {
      "name": "iconUrl",
      "description": "",
      "value": "\/ResourceServingWebapp\/rs\/tango\/0.8.90\/32x32\/categories\/applications-system.png"
    },
    "chromeStyle": {
      "name": "chromeStyle",
      "description": "",
      "value": "default"
    }
  }
}
```

Front-end widgets based on this JSON have to look for the `alternativeMaximizedLink` parameter and react accordingly.

**Comment by ChristianMurphy** [comment]
CI is warning that:

```
> Task :verifyGoogleJavaFormat FAILED
The following files are not formatted properly:
/home/travis/build/Jasig/uPortal/uPortal-api/uPortal-api-internal/src/main/java/org/apereo/portal/layout/dlm/remoting/registry/v43/PortletDefinitionBean.java
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':verifyGoogleJavaFormat'.
> Problems: formatting style violations
```

This can be cleared up with `./gradlew goJF`

**Comment by ChristianMurphy** [comment]
CI is reporting

```
> Task :uPortal-api:uPortal-api-internal:test

org.apereo.portal.portlets.layout.dlm.remoting.registry.v43.PortletDefinitionBeanTest > testEqualsDifferentID FAILED
    java.lang.AssertionError at PortletDefinitionBeanTest.java:209

111 tests completed, 1 failed

> Task :uPortal-api:uPortal-api-internal:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':uPortal-api:uPortal-api-internal:test'.
> There were failing tests. See the report at: file:///home/travis/build/Jasig/uPortal/uPortal-api/uPortal-api-internal/build/reports/tests/test/index.html
```

**Comment by drewwills** [comment]
Test failures taken care of.

**Pull request merged**
