### PR TITLE
UP-3780: Unescaped double quotes in layout.json break uMobile

### PR DESCRIPTION
**Pull request by jgribonvald**
and not only...

### CODE REVIEW

**Comment by asgrant** [comment]
👍

**Comment by cousquer** [comment]
:+1:

**Comment by jhelmer-unicon** [comment]
:+1:    Will mostly likely try to merge this sometime this week if there are not downvotes.

**Comment by jgribonvald** [comment]
Drew (from you mail) this can be merged

**Comment by asgrant** [comment]
+1

**Comment by drewwills** [comment]
Looks great.

**Pull request merged**
