### PR TITLE
UP-4419_fix: Fixed issue with collapsing sidebar and containing div height

### PR DESCRIPTION
**Pull request by doodelicious**
https://issues.jasig.org/browse/UP-4419

An issue was discovered regarding sidebar content and the 'Favorites' portlet new collapsible navbar - the containing div was not properly resizing when adding dynamic content to the list. This was corrected by overriding the max-height property found on the .navbar-collapse class and rewriting some of the styles and mark-up affected.

This issue DID NOT relate to https://issues.jasig.org/browse/UP-4424 as was previously noted. This issue was specific to the collapsible navbar added in the 'Favorites' portlet.

### CODE REVIEW

**Comment by drewwills** [comment]
What actually changed in content.xsl & respondr.xsl?  Both files show every line as a delta.

**Comment by timlevett** [comment]
@drewwills - if you add `?w=1` to the pr URL it removes whitespace changes. IE: `https://github.com/Jasig/uPortal/pull/531/files?w=1`

**Comment by drewwills** [comment]
### Warning

This PR includes the UP-4424 changes, which we're not ready to apply.

**Comment by drewwills** [comment]
@timlevett -- sweet!

**Comment by drewwills** [comment]
Merged out-of-band to detangle the desired fix from the unrelated changes that aren't ready.

**Pull request closed without merging**
