### PR TITLE
fix: updated encodeServiceUrl of the ticketValidationFilter bean to true

### PR DESCRIPTION
**Pull request by jonathanmtran**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

See https://groups.google.com/a/apereo.org/d/msg/uportal-user/44Uw1YP8_Mg/hLaTlEVZFAAJ

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by allanjackson** [comment]
Looks great, thanks!

**Comment by jgribonvald** [comment]
hi
did you validate this change with the embedded CAS ?

**Comment by allanjackson** [comment]
It does look like this breaks with the embedded cas server. So maybe the setting you need depends on both the version of the cas-client and the cas server?

**Comment by jonathanmtran** [comment]
Ouch. 

How does the following sound?
- make `encodeServiceUrl` a property, default it to `true` as it is the default for cas-client
- set the property in `uportal.properties` in uPortal-start to `false` with some verbiage and documentation

**Comment by jgribonvald** [comment]
At least a documentation is needed, after having an embedded CAS server into uPortal isn't a requirement, but it helps for tests !

**Pull request merged**
