### PR TITLE
Allow dynamic skin files to be stored in S3.   (updated for uPortal 5)

### PR DESCRIPTION
**Pull request by jhelmer-unicon**
https://issues.jasig.org/browse/UP-4677

This PR is a revamp of a previous PR that was created before the 5.x branch was created.

### CODE REVIEW

**Comment by bjagg** [comment]
@jhelmer-unicon We need to coordinate on this to get the changes merged before others create conflicts.

**Comment by ChristianMurphy** [comment]
@jhelmer-unicon merge conflicts have cropped up, could you resolve them?

**Comment by jhelmer-unicon** [comment]
Merge conflicts fixed.   I completely forgot this PR was still outstanding.   Baring down-votes, I'll probably try to get this merged in the next few days.

**Comment by ChristianMurphy** [comment]
@jhelmer-unicon Travis CI tests are timing out, during cobertura.
There is an exception happening https://travis-ci.org/Jasig/uPortal/builds/202711024#L5986
But that same exception appears to be happening on `master` https://travis-ci.org/Jasig/uPortal/builds/202722019#L6205

**Comment by ChristianMurphy** [comment]
@jhelmer-unicon any update on this?

**Comment by ChristianMurphy** [comment]
@jhelmer-unicon a merge conflict has cropped up, could you resolve it?

**Pull request merged**
