### PR TITLE
UP-3413: JSR-168 Backfill

### PR DESCRIPTION
**Pull request by MichaelVose2**
Hello.

@ChristianMurphy  I have reapplied to my changes to a new repo as I was unable to rebase, hence this new PR.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Thanks @MichaelVose2!
It looks like this PR is missing the code style changes you made in #711
Would you be able to reapply those here?

**Comment by bjagg** [comment]
Are we still waiting on the style changes?

**Comment by ChristianMurphy** [comment]
@bjagg Yes still waiting

**Comment by MichaelVose2** [comment]
Hello,

Sorry;  I was away for 2 weeks and was unable to do the required work until today.

I’ve just pushed the commits which will hopefully ensure the code utilised the required styleguide.

To be clear I’ve utilised 4 spaces, instead of tabbing, along with standard sub child selectors etc.

Other than that I am unsure as to what the styleguide for LESS should be (as presumably it would follow a JavaScript styleguide, and not the java one).

Kindly,

**Comment by bjagg** [comment]
Michael, have you submitted a CLA?
https://github.com/Jasig/WebproxyPortlet#-contribution-guidelines applies to uPortal as well

**Comment by cousquer** [comment]
@bjagg @MichaelVose2 @ChristianMurphy 
I just had an email exchange with Michael, he will send you one quickly. If not already done.
:wink:

**Comment by MichaelVose2** [comment]
Hi,

I can only do this on the third of January,

Kindly
________________________________

**Comment by MichaelVose2** [comment]
Hello,

I have just signed and ICLA and emailed it to the appropriate email.

Kindly.

**Pull request merged**
