### PR TITLE
UP-4483: Add caching to member collections of PAGS Group and Test Group

### PR DESCRIPTION
**Pull request by bjagg**
After a lot of research and experimentation, I stumbled across the fix - cache the collection members of the PAGS entities. This creates a cache for each member and then uses the underlying cache (finally) for the entity.

### CODE REVIEW

**Comment by drewwills** [comment]
Good catch.  What's the best way to capture & disseminate the "lessons learned" here?

**Comment by jameswennmacher** [comment]
+1 in a huge way.  Great improvement.  

Please port this back to rel-4-2-patches as well.  Benito the only improvement I can suggest is that during the Spring context initialization I see the following messages.  Could you add the cache definitions to ehcache as part of this PR?

WARN  [localhost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory 2016-02-10 09:06:38,565 - HHH020003: Could not find a specific ehcache configuration for cache named [org.jasig.portal.groups.pags.dao.jpa.PersonAttributesGroupDefinitionImpl.testGroups]; using defaults.
WARN  [localhost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory 2016-02-10 09:06:38,574 - HHH020003: Could not find a specific ehcache configuration for cache named [org.jasig.portal.groups.pags.dao.jpa.PersonAttributesGroupTestGroupDefinitionImpl.tests]; using defaults.

**Comment by bjagg** [comment]
Great question. Maybe a blog post? An Apereo session sharing the experience of improving Entity PAGS might be rather short.

**Comment by bjagg** [comment]
Will do, James.

**Comment by jameswennmacher** [comment]
For knowledge sharing I'll suggest  one or more of:
* an email to uportal-dev list
* If you have enough for a blog that's great, but it might make sense to add it to a personal blog or a dev-tips or lessons learned section of the Apereo uPortal wiki.

**Comment by jameswennmacher** [comment]
BTW I'm good for you merging this PR after you add the cache definitions, and merge it into rel-4-2-patches too.

**Comment by drewwills** [comment]
+1 for merge to master and to rel-4-2-patches

**Comment by timlevett** [comment]
:+1: for master/rel-4-2-patches

**Pull request merged**
