### PR TITLE
fix(oidc-token): provide customclaims as multivalued attributes

### PR DESCRIPTION
**Pull request by jgribonvald**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [ ] tests are included
-   [ ] documentation is changed or added
-   [ ] [message properties][] have been updated with new phrases
-   [ ] view conforms with [WCAG 2.0 AA][]

##### Description of change

Provide all user attributes defined in org.apereo.portal.security.oauth.IdTokenFactory.customClaims as multivalued.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jgribonvald** [comment]
I think it's the better way to obtains user attributes instead of using api **/api/v5-0/people/me**

**Comment by drewwills** [comment]
This is a great change -- it's something we need.
I hope to take a look at this one (and the dialects one too) shortly.

**Comment by drewwills** [comment]
Sample JWT with this  change applied:

```
{
  "iss": "http://localhost:8080/uPortal",
  "sub": "jdoe",
  "aud": "http://localhost:8080/uPortal",
  "exp": 1532590453,
  "iat": 1532558053,
  "name": "Jane Doe",
  "given_name": "Jane",
  "family_name": "Doe",
  "groups": [
    "Students"
  ],
  "Student": [
    "A_572",
    "F_571",
    "A_571",
    "C_571",
    "A_576"
  ]
}
```
Looks perfect!  :+1: 
Time to merge.

**Pull request merged**
