### PR TITLE
UP-4741: Merge usefull commits from master into rel-4-3-patches

### PR DESCRIPTION
**Pull request by jgribonvald**
It would be great to merge these commits from master (before packaging renaming) into rel-4.3-patches branch. Why it's needed ?
- They improve the portal (somes are for performance, bugs resolution, UI improvments, etc...)
- If we need to wait version 5.0 to benefit of it it will take too much times, why waiting whereas change are already here ?
- If we need to go on version 5.0 it will take too much time on migration (when seeing the roadmap and change planned)
- If we need to go on version 5.0 with all change planned migration won't be easy and will discourage a lot ! So we will wait again a log of time before to benefit of it !

### CODE REVIEW

**Comment by jgribonvald** [comment]
For information I've made a "git rebase ad0f1abc8e8798e8b4ded6147e188884d08c834f" on rel-4-3-patches, I added theses commits  0f4699e +  58605c7 +   48345e8 + 2373936 and removed 983d622

**Comment by jgribonvald** [comment]
@ChristianMurphy I don't how you can see there is duplicated code, as it's a rebase it's "normal" that some commits were rewritten, and I can't see duplicated code.

After about conflicts I had them too during my merge, but I don't know how to solve it here due to my rebase.

If you have a better way to make the PR I'm aware and will try to follow yourth, but maybe the best is that someone who has a write access do the same rebase. I never made a such request with PR so I don't know how to do that in the best way. But known that I made some commits to be able to use somes PR in the good uportal version and that I removed somes other to stay in version.

**Comment by ChristianMurphy** [comment]
> I don't how you can see there is duplicated code, as it's a rebase it's "normal" that some commits were rewritten, and I can't see duplicated code.

You're right, the code is not duplicated, the version control history is duplicated.
Duplicated commits will not cause any issues in the portal :ship: , but can confuse version control tools like [`git bisect`](https://git-scm.com/docs/git-bisect) and [`git blame`](https://git-scm.com/docs/git-blame). :confused: 

> After about conflicts I had them too during my merge, but I don't know how to solve it here due to my rebase.

`git pull https://github.com/Jasig/uPortal rel-4-3-patches` should allow for resolving the merge conflicts. :100: 

> If you have a better way to make the PR I'm aware and will try to follow yourth, but maybe the best is that someone who has a write access do the same rebase. I never made a such request with PR so I don't know how to do that in the best way.

Rebasing on an active branch like `rel-4-3-patches` or `master` can be risky. :warning: 
Using [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) for each commit that needs to be back ported is usually the safest option. :white_check_mark: 

> But known that I made some commits to be able to use somes PR in the good uportal version and that I removed somes other to stay in version.

Thanks! Avoiding [semver major](http://semver.org/lang/fr/) changes will definitely speed the merge process. :smile:

**Comment by jgribonvald** [comment]
Ok, so I have again some work !

I don't have time now to do again this work but I will try in next weeks...
After for conflits I will watch on, it's a problems, yes.

**Comment by jgribonvald** [comment]
One question is the git rebase --onto could replace the cherry-pick ? as there is a lot of commits and merge (wich do some change on commits) in the master branch to merge in 4.3.

**Comment by ChristianMurphy** [comment]
> One question is the `git rebase --onto` could replace the `cherry-pick`?

Sadly, that would have the same duplicated commit side effect as `git rebase` or `git merge`. :disappointed: 

> as there is a lot of commits and merge (which do some change on commits) in the master branch to merge in 4.3.

Running `git cherry-pick` on many commits takes time :clock10:, but it is the best way that I am aware of :8ball:.

**Comment by cousquer** [comment]
👍🏻 for cherry-pick, 😭

**Comment by drewwills** [comment]
Folks -- this PR appears to be way too much stuff to apply back to the rel-4-3-patches branch.  Was this a merge?  I support cherry-picking individual items that match our policies for Semantic Versioning, but we should probably tackle those 1 or 2 at a time.

**Comment by cousquer** [comment]
@jgribonvald @drewwills @ChristianMurphy @apetro 
Do not worry about conflict with i18n/Messages_fr.properties. 😉  
`uportal-war/src/main/resources/properties/i18n/Messages_fr.properties`
if there is a problem with : 
`uportal-war/src/main/webapp/media/skins/respondr/common/less/navigation.less`
I'm sure @ChristianMurphy and I could solve that very quickly

**Comment by auxepaul** [comment]
+1 Usefull

**Comment by jgribonvald** [comment]
I solved conflicts in the github tool in-line, so please check on uportal-war/src/main/resources/properties/i18n/Messages_fr.properties and uportal-war/src/main/webapp/media/skins/respondr/common/less/navigation.less before

For the cherry-pick I won't have time until several weaks now :(

**Comment by drewwills** [comment]
Folks -- I really appreciate the effort and the care being shown in this PR and in others as well.  I am as eager as anyone to build the best uPortal we can possibly have.

I just don't see how this PR can be saved (merged).  We absolutely do merge new contributions to `master` back down to `rel-4-3-patches`, but ONLY if they match our [community-adopted policies for versioning](http://semver.org/), and we really must consider them one-at-a-time (not in a wholesale merge).

I'm going to close this PR in 48 hours (or whenever I get back to it after 48 hours) unless there is vigorous disagreement.

**Comment by jgribonvald** [comment]
Drew, I understand your point of view but is it possible to let this PR open until I rebuilt it  ? I didn't have a lot of time to do this work but I will be able to redo it in few weeks.

After all these commits aren't needed in up 4.3 branch, but many solve bugs or problems like the pags guestTester, few offcanvas improvments needed, and different fix that make up-4.3 "usable" without too much effort. If French communities come on this branch without it they will think of again an unstable release, with a lot of work before running on and they will think more on going to an other solution  !

**Comment by drewwills** [comment]
@jgribonvald -- We can leave the PR open for reference, for a time.

Fixes to `master` that can & should go into `rel-4-3-patches` should be applied there _at the same time_ they are applied to `master`.  It should be indicated in the issue ticket.  This is something I always watch for in the work that I do, and I always think about it when I'm processing pull requests from others.

How many commits that can be merged from `master` into `rel-4-3-patches` are you really going to find?  I'm certain -- I'll readily admit -- that there must be one or two (or about a handful).  I also agree that there is value in finding them and applying them.

They need to be identified, discussed, and worked into `rel-4-3-patches` individually -- each in its own PR.  But I think you will find (more often than not) that the commits you find will not go in "cleanly;"  either...

 - There will be a conflict when you `$ git cherry-pick`;  or
 - The commit(s) contain mixed changes:  some changes that _should_ go into `rel-4-3-patches` and some that _shouldn't_

We'd love to have them (in the earlier branch), but we need to process them carefully and deal with these nuances.

**Comment by ChristianMurphy** [comment]
@jgribonvald rest assured that the commits made remain safely stored on your branch and the diff in this PR can be viewed regardless of whether the PR is opened or closed. 😌 

Because this PR includes API breaking changes, it cannot be accepted into `rel-4-3-patches`, it would cause instability for institutions already running on `rel-4-3-patches`.  😨 

Thanks for taking the time to put this together. 🙇 
More targeted backports of non API breaking patches are welcome. 👍

**Pull request closed without merging**
