### PR TITLE
UP-4856: Add gradle lint

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [x] tests are included

##### Description of change

<https://issues.jasig.org/browse/UP-4856>

Use [gradle lint](https://github.com/nebula-plugins/gradle-lint-plugin) to detect common gradle configuration issues.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
```
error     duplicate-dependency-class         commons-beanutils:commons-beanutils:1.7.0 in configuration ':uPortal-api:uPortal-api-rest:compile' has 10 classes duplicated by commons-collections:commons-collections:3.2.2 (use --info for detailed class list) (no auto-fix available)
```

https://travis-ci.org/Jasig/uPortal/builds/238165333#L720

**Comment by ChristianMurphy** [comment]
```
Duplicate classes: [
    org/apache/commons/collections/FastHashMap, org/apache/commons/collections/Buffer,
    org/apache/commons/collections/FastHashMap$CollectionView$CollectionViewIterator, 
    org/apache/commons/collections/FastHashMap$CollectionView, 
    org/apache/commons/collections/ArrayStack, 
    org/apache/commons/collections/FastHashMap$EntrySet, 
    org/apache/commons/collections/FastHashMap$KeySet, 
    org/apache/commons/collections/FastHashMap$1, 
    org/apache/commons/collections/FastHashMap$Values, 
    org/apache/commons/collections/BufferUnderflowException
]
```

**Comment by ChristianMurphy** [comment]
https://stackoverflow.com/questions/14402745/duplicate-classes-in-commons-collections-and-commons-beanutils

**Comment by ChristianMurphy** [comment]
after sync there are new errors

```
error
duplicate-dependency-class
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-portlets:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3

error
duplicate-dependency-class
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-rendering:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3

error
duplicate-dependency-class
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-web:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3

error
duplicate-dependency-class
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-soffit:uPortal-soffit-renderer:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3
```

**Comment by ChristianMurphy** [comment]
full log

```
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-marketplace:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3. Duplicate classes: [org/hamcrest/Matcher, org/hamcrest/core/CombinableMatcher, org/hamcrest/TypeSafeMatcher, org/hamcrest/internal/SelfDescribingValue, org/hamcrest/Description$NullDescription, org/hamcrest/MatcherAssert, org/hamcrest/core/AllOf, org/hamcrest/Condition$Step, org/hamcrest/core/IsNot, org/hamcrest/core/IsSame, org/hamcrest/core/IsNull, org/hamcrest/core/IsAnything, org/hamcrest/Condition, org/hamcrest/core/AnyOf, org/hamcrest/CustomMatcher, org/hamcrest/StringDescription, org/hamcrest/core/Is, org/hamcrest/Condition$NotMatched, org/hamcrest/core/IsInstanceOf, org/hamcrest/core/StringContains, org/hamcrest/internal/ReflectiveTypeFinder, org/hamcrest/BaseDescription, org/hamcrest/Condition$Matched, org/hamcrest/CoreMatchers, org/hamcrest/core/StringEndsWith, org/hamcrest/internal/ArrayIterator, org/hamcrest/internal/SelfDescribingValueIterator, org/hamcrest/core/ShortcutCombination, org/hamcrest/core/Every, org/hamcrest/core/IsCollectionContaining, org/hamcrest/SelfDescribing, org/hamcrest/core/CombinableMatcher$CombinableBothMatcher, org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher, org/hamcrest/Condition$1, org/hamcrest/core/IsEqual, org/hamcrest/core/SubstringMatcher, org/hamcrest/Factory, org/hamcrest/FeatureMatcher, org/hamcrest/CustomTypeSafeMatcher, org/hamcrest/core/DescribedAs, org/hamcrest/core/StringStartsWith, org/hamcrest/DiagnosingMatcher, org/hamcrest/BaseMatcher, org/hamcrest/Description, org/hamcrest/TypeSafeDiagnosingMatcher]
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-portlets:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3. Duplicate classes: [org/hamcrest/Matcher, org/hamcrest/Condition, org/hamcrest/CustomMatcher, org/hamcrest/StringDescription, org/hamcrest/SelfDescribing, org/hamcrest/core/SubstringMatcher, org/hamcrest/Description, org/hamcrest/TypeSafeMatcher, org/hamcrest/core/AllOf, org/hamcrest/internal/ReflectiveTypeFinder, org/hamcrest/internal/SelfDescribingValue, org/hamcrest/MatcherAssert, org/hamcrest/core/IsNull, org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher, org/hamcrest/core/StringStartsWith, org/hamcrest/Condition$NotMatched, org/hamcrest/Condition$1, org/hamcrest/FeatureMatcher, org/hamcrest/CustomTypeSafeMatcher, org/hamcrest/core/CombinableMatcher, org/hamcrest/core/Is, org/hamcrest/core/ShortcutCombination, org/hamcrest/core/IsEqual, org/hamcrest/TypeSafeDiagnosingMatcher, org/hamcrest/Condition$Step, org/hamcrest/core/IsNot, org/hamcrest/core/StringContains, org/hamcrest/core/CombinableMatcher$CombinableBothMatcher, org/hamcrest/Factory, org/hamcrest/core/DescribedAs, org/hamcrest/DiagnosingMatcher, org/hamcrest/BaseMatcher, org/hamcrest/Condition$Matched, org/hamcrest/CoreMatchers, org/hamcrest/core/Every, org/hamcrest/core/IsCollectionContaining, org/hamcrest/Description$NullDescription, org/hamcrest/core/IsSame, org/hamcrest/core/IsAnything, org/hamcrest/core/AnyOf, org/hamcrest/core/IsInstanceOf, org/hamcrest/BaseDescription, org/hamcrest/core/StringEndsWith, org/hamcrest/internal/ArrayIterator, org/hamcrest/internal/SelfDescribingValueIterator]
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-rendering:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3. Duplicate classes: [org/hamcrest/Matcher, org/hamcrest/core/CombinableMatcher, org/hamcrest/TypeSafeMatcher, org/hamcrest/internal/SelfDescribingValue, org/hamcrest/Description$NullDescription, org/hamcrest/MatcherAssert, org/hamcrest/core/AllOf, org/hamcrest/Condition$Step, org/hamcrest/core/IsNot, org/hamcrest/core/IsSame, org/hamcrest/core/IsNull, org/hamcrest/core/IsAnything, org/hamcrest/Condition, org/hamcrest/core/AnyOf, org/hamcrest/CustomMatcher, org/hamcrest/StringDescription, org/hamcrest/core/Is, org/hamcrest/Condition$NotMatched, org/hamcrest/core/IsInstanceOf, org/hamcrest/core/StringContains, org/hamcrest/internal/ReflectiveTypeFinder, org/hamcrest/BaseDescription, org/hamcrest/Condition$Matched, org/hamcrest/CoreMatchers, org/hamcrest/core/StringEndsWith, org/hamcrest/internal/ArrayIterator, org/hamcrest/internal/SelfDescribingValueIterator, org/hamcrest/core/ShortcutCombination, org/hamcrest/core/Every, org/hamcrest/core/IsCollectionContaining, org/hamcrest/SelfDescribing, org/hamcrest/core/CombinableMatcher$CombinableBothMatcher, org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher, org/hamcrest/Condition$1, org/hamcrest/core/IsEqual, org/hamcrest/core/SubstringMatcher, org/hamcrest/Factory, org/hamcrest/FeatureMatcher, org/hamcrest/CustomTypeSafeMatcher, org/hamcrest/core/DescribedAs, org/hamcrest/core/StringStartsWith, org/hamcrest/DiagnosingMatcher, org/hamcrest/BaseMatcher, org/hamcrest/Description, org/hamcrest/TypeSafeDiagnosingMatcher]
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-web:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3. Duplicate classes: [org/hamcrest/Matcher, org/hamcrest/Condition, org/hamcrest/CustomMatcher, org/hamcrest/StringDescription, org/hamcrest/SelfDescribing, org/hamcrest/core/SubstringMatcher, org/hamcrest/Description, org/hamcrest/TypeSafeMatcher, org/hamcrest/core/AllOf, org/hamcrest/internal/ReflectiveTypeFinder, org/hamcrest/internal/SelfDescribingValue, org/hamcrest/MatcherAssert, org/hamcrest/core/IsNull, org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher, org/hamcrest/core/StringStartsWith, org/hamcrest/Condition$NotMatched, org/hamcrest/Condition$1, org/hamcrest/FeatureMatcher, org/hamcrest/CustomTypeSafeMatcher, org/hamcrest/core/CombinableMatcher, org/hamcrest/core/Is, org/hamcrest/core/ShortcutCombination, org/hamcrest/core/IsEqual, org/hamcrest/TypeSafeDiagnosingMatcher, org/hamcrest/Condition$Step, org/hamcrest/core/IsNot, org/hamcrest/core/StringContains, org/hamcrest/core/CombinableMatcher$CombinableBothMatcher, org/hamcrest/Factory, org/hamcrest/core/DescribedAs, org/hamcrest/DiagnosingMatcher, org/hamcrest/BaseMatcher, org/hamcrest/Condition$Matched, org/hamcrest/CoreMatchers, org/hamcrest/core/Every, org/hamcrest/core/IsCollectionContaining, org/hamcrest/Description$NullDescription, org/hamcrest/core/IsSame, org/hamcrest/core/IsAnything, org/hamcrest/core/AnyOf, org/hamcrest/core/IsInstanceOf, org/hamcrest/BaseDescription, org/hamcrest/core/StringEndsWith, org/hamcrest/internal/ArrayIterator, org/hamcrest/internal/SelfDescribingValueIterator]
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-webapp:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3. Duplicate classes: [org/hamcrest/Matcher, org/hamcrest/Condition, org/hamcrest/CustomMatcher, org/hamcrest/StringDescription, org/hamcrest/SelfDescribing, org/hamcrest/core/SubstringMatcher, org/hamcrest/Description, org/hamcrest/TypeSafeMatcher, org/hamcrest/core/AllOf, org/hamcrest/internal/ReflectiveTypeFinder, org/hamcrest/internal/SelfDescribingValue, org/hamcrest/MatcherAssert, org/hamcrest/core/IsNull, org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher, org/hamcrest/core/StringStartsWith, org/hamcrest/Condition$NotMatched, org/hamcrest/Condition$1, org/hamcrest/FeatureMatcher, org/hamcrest/CustomTypeSafeMatcher, org/hamcrest/core/CombinableMatcher, org/hamcrest/core/Is, org/hamcrest/core/ShortcutCombination, org/hamcrest/core/IsEqual, org/hamcrest/TypeSafeDiagnosingMatcher, org/hamcrest/Condition$Step, org/hamcrest/core/IsNot, org/hamcrest/core/StringContains, org/hamcrest/core/CombinableMatcher$CombinableBothMatcher, org/hamcrest/Factory, org/hamcrest/core/DescribedAs, org/hamcrest/DiagnosingMatcher, org/hamcrest/BaseMatcher, org/hamcrest/Condition$Matched, org/hamcrest/CoreMatchers, org/hamcrest/core/Every, org/hamcrest/core/IsCollectionContaining, org/hamcrest/Description$NullDescription, org/hamcrest/core/IsSame, org/hamcrest/core/IsAnything, org/hamcrest/core/AnyOf, org/hamcrest/core/IsInstanceOf, org/hamcrest/BaseDescription, org/hamcrest/core/StringEndsWith, org/hamcrest/internal/ArrayIterator, org/hamcrest/internal/SelfDescribingValueIterator]
org.hamcrest:hamcrest-all:1.3 in configuration ':uPortal-soffit:uPortal-soffit-renderer:testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3. Duplicate classes: [org/hamcrest/Matcher, org/hamcrest/Condition, org/hamcrest/CustomMatcher, org/hamcrest/StringDescription, org/hamcrest/SelfDescribing, org/hamcrest/core/SubstringMatcher, org/hamcrest/Description, org/hamcrest/TypeSafeMatcher, org/hamcrest/core/AllOf, org/hamcrest/internal/ReflectiveTypeFinder, org/hamcrest/internal/SelfDescribingValue, org/hamcrest/MatcherAssert, org/hamcrest/core/IsNull, org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher, org/hamcrest/core/StringStartsWith, org/hamcrest/Condition$NotMatched, org/hamcrest/Condition$1, org/hamcrest/FeatureMatcher, org/hamcrest/CustomTypeSafeMatcher, org/hamcrest/core/CombinableMatcher, org/hamcrest/core/Is, org/hamcrest/core/ShortcutCombination, org/hamcrest/core/IsEqual, org/hamcrest/TypeSafeDiagnosingMatcher, org/hamcrest/Condition$Step, org/hamcrest/core/IsNot, org/hamcrest/core/StringContains, org/hamcrest/core/CombinableMatcher$CombinableBothMatcher, org/hamcrest/Factory, org/hamcrest/core/DescribedAs, org/hamcrest/DiagnosingMatcher, org/hamcrest/BaseMatcher, org/hamcrest/Condition$Matched, org/hamcrest/CoreMatchers, org/hamcrest/core/Every, org/hamcrest/core/IsCollectionContaining, org/hamcrest/Description$NullDescription, org/hamcrest/core/IsSame, org/hamcrest/core/IsAnything, org/hamcrest/core/AnyOf, org/hamcrest/core/IsInstanceOf, org/hamcrest/BaseDescription, org/hamcrest/core/StringEndsWith, org/hamcrest/internal/ArrayIterator, org/hamcrest/internal/SelfDescribingValueIterator]
```

**Comment by drewwills** [comment]
This change seems like a good thing to have.

**Pull request merged**
