### PR TITLE
UP-4779:  Add an icon next to every item in the Favorites portlet

### PR DESCRIPTION
**Pull request by drewwills**
https://issues.jasig.org/browse/UP-4779

favorites-icons

### CODE REVIEW

**Comment by cousquer** [comment]
@drewwills @ChristianMurphy @apetro
> Toby AWWWW Tuesday 18 October 2016 15:52
> Up until recently we had the default generic icon for 70%+ of our portlets in the customize tray. I recently went through and gave most of them an icon from the default icons that uPortal ships with. I'd love to be even as far as you.

>>On Monday, October 17, 2016 at 5:09:25 PM UTC-5, aYYYYY wrote:
We're using Font Awesome pretty much across the board.
>>drew

**Comment by cousquer** [comment]
>>>I think there's some way to have custom icon fonts?
Could be a separate project of Apereo Fundation in incubation.
cause if there is something that can be in common to other projects, that could be a big open-source app/action/brand icon set. not easy but doable.

**Comment by drewwills** [comment]
Thanks guys!

**Comment by cousquer** [comment]
@drewwills 
Dydh da
Meur ras
Chons da!

**Pull request merged**
