### PR TITLE
fix(#1217): Change name from 100,000 length clob to 4,000 varchar.

### LINKED ISSUE #1217: Multiple text columns not supported by older Oracle versions.
Older Oracle versions, more accurately the Hibernate dialects, do not support multiple text (LONG) columns in a single table. Only PortletPerferenceImpl.java currently defines such a thing.

### PR DESCRIPTION
**Pull request by bjagg**
Resolves #1217.

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
To which branch are we going to apply this change?
What can be done to update an existing schema automatically?

**Comment by bjagg** [comment]
Updated to force CLOB for Oracle and other databases that match previous schema.

**Comment by drewwills** [comment]
Do it have it right -- this solution now (1) works on Oracle, and (2) doesn't alter the schema from previous?

**Comment by ChristianMurphy** [comment]
@bjagg does this PR both:

> (1) work on Oracle, and (2) doesn't alter the schema from previous?

**Comment by bjagg** [comment]
It works with Oracle and it does seem to work with existing schemas.

**Pull request merged**
