### PR TITLE
UP-4071 : portlet-definition syntactic sugar for granting BROWSE permission

### PR DESCRIPTION
**Pull request by jhelmer-unicon**
...inition.xml file.

https://issues.jasig.org/browse/UP-4071

### CODE REVIEW

**Comment by vertein** [comment]
:+1: Here we go!

**Comment by vertein** [comment]
Oh, wait, my excitement has been tempered by not being able to automatically merge this.  @jhelmer-unicon , as soon as it's ready to merge, I'll be more than happy to hit the green button.

**Comment by jhelmer-unicon** [comment]
@vertein Hey Tim.   Sorry, missed that this had merge conflicts.   I believe it should be good to go now.

**Comment by apetro** [comment]
More usable syntax for importing portlet definitions with the right permissions around them is a wonderful thing.  I'm really looking forward to this feature.

Trying to think through some edge cases.  What happens if I grant `BROWSE` through the permissions element in `portlet-definition` entities, run that import, and then change that `portlet-definition` file as regards who is granted `BROWSE`, and run the import again?  Do the `BROWSE` permission grants accumulate or does the subsequent import replace the grants in the previous import?

**Comment by vertein** [comment]
@jhelmer-unicon Hey, sorry, didn't see your message earlier, or I would have merged sooner.

**Pull request merged**
