### PR TITLE
UP-4731: Upgrade xStream and Commons BeanUtils

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

See description in ticket [UP-4731](https://issues.jasig.org/browse/UP-4731).

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
Looks like a pretty simple -- and valuable -- update... have you run a build with this change locally?

**Comment by ChristianMurphy** [comment]
@drewwills I have tested the build itself.
However without ability to build to maven local, I have not been able to click test this yet.

**Comment by drewwills** [comment]
I will get around to running this change before too long (it's a busy week).

Here's what it takes...
  1. Run a `$ ./gradlew clean install on `uPortal`
  1. Change the `uPortalVersion` property in `uPortal-start` to `5.0.0-SNAPSHOT`
  1. Run `$ ./gradlew clean portalDeploy` in `uPortal-start`
  1. Start up the portal & click around

**Comment by drewwills** [comment]
I just followed the steps I listed above.  Everything seems to work.

**Pull request merged**
