### PR TITLE
UP-4756: Ensure links have a valid href destination - master

### PR DESCRIPTION
**Pull request by ChristianMurphy**
#### Issue

https://issues.jasig.org/browse/UP-4756

Anchor element found with a valid href attribute, but no link content has been supplied.

``` html
<a href="javascript:;"> ...</a>
```
#### Resolution

Use empty anchor instead.

``` html
<a href="#"> ...</a>
```

#### :warning: Note :warning: 

This change will drop support for older browsers where `href="#"` can cause page reload.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
See additional context in #743

**Comment by bjagg** [comment]
@ChristianMurphy a few merge conflicts now exist

**Comment by ChristianMurphy** [comment]
@bjagg will do, also note this PR could use some additional manual click testing.

**Comment by cousquer** [comment]
click and touch testing...

**Comment by bjagg** [comment]
I will "kick the tires" a bit more than some of the other PRs

**Comment by bjagg** [comment]
Reviewed changes and did quite a bit of spot-checking around admin tools and layout preferences.  Good job!

**Comment by ChristianMurphy** [comment]
Thanks @bjagg !

**Pull request merged**
