### PR TITLE
fix: missing conf on serveral server name management when activating …

### PR DESCRIPTION
**Pull request by jgribonvald**
…cas guest redirect

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [ ] tests are included
-   [ ] documentation is changed or added
-   [ ] [message properties][] have been updated with new phrases
-   [ ] view conforms with [WCAG 2.0 AA][]

##### Description of change

This change must solve the issue #1409 (tested locally)

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jgribonvald** [comment]
After watching where the property `cas.enable.redirect.guest.to.login` is used I've found a "nonsense" configuration:

**Comment by jgribonvald** [comment]
After watching where the property `cas.enable.redirect.guest.to.login` is used I've found a "nonsense" configuration:
the file `security.properties` set the property `cas.enable.redirect.guest.to.login=false` whereas the bean is defined with this property with a default value
```xml
<bean name="casAuthenticationFilter" class="org.apereo.portal.spring.web.OptionalFilterDecorator">
        <property name="wrappedFilter" ref="casInnerAuthenticationFilter" />
        <property name="enable" value="${cas.enable.redirect.guest.to.login:false}" />
    </bean>
```

So I could purpose a PR with removing the property setted into `security.properties`, what do you think ?

**Comment by drewwills** [comment]
So I could purpose a PR with removing the property setted into security.properties, what do you think ?

We need to ask ourselves:  "what's the best way to set up properties that have defaults, so that someone who may want to change the value of the property is most likely to discover it?"

I believe the presence of the property in `security.properties` is only for the sake of discoverability.  Often we have included these sorts of properties (i.e. with defaults defined in `@Value` annotations) in the properties files anyway, with comments, and commented-out.

Perhaps that's the best approach.  I don't think someone looking to configure uPortal will comb through .java files to figure out the options, but s/he may look at .properties files.  (And of course we should add it to the documentation.)

**Comment by jgribonvald** [comment]
> ```
> Perhaps that's the best approach. I don't think someone looking to configure uPortal will comb through .java files to figure out the options, but s/he may look at .properties files. (And of course we should add it to the documentation.)

From my point of view removing the property from security.properties is good if we document on how to activate the mode !

**Comment by jgribonvald** [comment]
A little reminder to reviewers.
I know you had thanksgiving so you had some vacations :wink:

**Comment by drewwills** [comment]
I'm looking at this item now.

When I build this branch and use it in uPortal-start, the `cas.enable.redirect.guest.to.login` property correctly sends me to the login form instead of the guest layout.

But when I try to authenticate with CAS, I get the following...

cas-403

**Comment by drewwills** [comment]
There's another potential problem (related to this one) brewing here:  https://github.com/Jasig/uPortal/blob/ae8be7877ad9e0f82fd23335c510ae1cff9f0308/uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java#L59

**Comment by mrapczynski** [comment]
@drewwills Assuming the issue here is what happens when the value not supplied? I dealt with something similar in another project where I am using Spring. Those `@Value` annotations support a default/fallback. Would it be sensible to add a default value, yet still leaving open the option for the implementer to customize?

> There's another potential problem (related to this one) brewing here:
> 
> [uPortal/uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java](https://github.com/Jasig/uPortal/blob/ae8be7877ad9e0f82fd23335c510ae1cff9f0308/uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java#L59)
> 
> Line 59 in [ae8be78](/Jasig/uPortal/commit/ae8be7877ad9e0f82fd23335c510ae1cff9f0308)
>  @Value("${portal.protocol.server.context}")

**Comment by drewwills** [comment]
@mrapczynski -- Specifying defaults on `@Value` annotations is a very cool feature that definitely helps us out of a lot of tight spots.

There's probably more we could do with that feature in this area, but I think the heart of the matter is that a custom (roll-your-own) replacement token -- `_CURRENT_SERVER_NAME_` -- is being used in is a property that feeds several Spring EL different expressions.  Spring isn't aware of it, so it can't help us.

**Comment by drewwills** [comment]
Folks -- please take a look at #1470.

**Comment by jgribonvald** [comment]
> I'm looking at this item now.
> 
> When I build this branch and use it in uPortal-start, the `cas.enable.redirect.guest.to.login` property correctly sends me to the login form instead of the guest layout.
> 
> But when I try to authenticate with CAS, I get the following...
> 
> cas-403

You get this issue due to encodeServiceUrl=true ! If you watch better you will see the error is on the serviceUrl, in one case it's encoded in the other not, this depends on the client cas and cas server version sometimes you should activate it sometimes not. If you watch on the other CAS defintion bean you will see that this option is also set to false ;)

Sorry I didn't change this value because on my server CAS version there isn't problem !

**Comment by jgribonvald** [comment]
> There's another potential problem (related to this one) brewing here:
> 
> [uPortal/uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java](https://github.com/Jasig/uPortal/blob/ae8be7877ad9e0f82fd23335c510ae1cff9f0308/uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java#L59)
> 
> Line 59 in [ae8be78](/Jasig/uPortal/commit/ae8be7877ad9e0f82fd23335c510ae1cff9f0308)
>  @Value("${portal.protocol.server.context}")

About this potential issue I'm open to talk and I don't know how to manage it as I don't know the usage ! I don't know the goal a this property in the OIDC as any request it already done on the good URL. =>  I don't know where and on what it could be used.

**Comment by ChristianMurphy** [comment]
@drewwills @jgribonvald any decision on whether to move forward with this or #1470?

**Comment by ChristianMurphy** [comment]
Thanks @jgribonvald and @bjagg! :bowing_man:

**Pull request merged**
