### PR TITLE
UP-4649:  Round Two removing orphaned code with UCDetector

### PR DESCRIPTION
**Pull request by drewwills**
https://issues.jasig.org/browse/UP-4649

Same diligence practices were applied to these items as previous...
  - UCDetector
  - IDE (double-check for references)
  - $grep (look in Spring, Import/Export, groovy tests, _etc._)
  - $ant clean initportal (complete rebuild, tests run)
  - $ant data-export (run complete export as well)

### CODE REVIEW

**Comment by timlevett** [comment]
Assuming you did a startup and full regression test as well?

**Comment by timlevett** [comment]
Also had the thought, quickstart full build and startup?

**Comment by timlevett** [comment]
:+1: always good to cleanup unused code.

**Comment by drewwills** [comment]
Building/testing quickstart is a part of the release checklist (so it's about to happen, in fact).  All of the quickstart data is used in this diligence process.  There isn't much chance of hurting the quickstart by pulling lines of code out of uportal-war.

**Pull request merged**
