### PR TITLE
UP4712: Fix logic error with GroupMemberImpl.primGetAncestorGroups()

### PR DESCRIPTION
**Pull request by bjagg**
https://issues.jasig.org/browse/UP-4712

## Next Steps

- [x] Apply to rel-4-3-patches
- [x] Apply to master, but after the Gradle refactor

### CODE REVIEW

**Comment by phillips1021** [comment]
After applying this change the portal statistics portlet now shows our groups correctly

**Comment by drewwills** [comment]
Thanks @bjagg!

**Comment by drewwills** [comment]
### General Note on New Pull Requests

Please hold off on merging pull requests to `master` for a brief period.  A significant refactor is already underway for uPortal 5, and the potential for difficult conflicts is large.  I'll do my best to make this change happen quickly.  Thank you for your patience.

**Comment by phillips1021** [comment]
Drew - I can make this change manually in my own code base so no rush on merging this into master.

However, portal statistics has been broken for some time since the last "official release (4.3.0)" - along with other major broken parts in the last official release --  so from a community perspective it would be great if someone cut a new "official release" that has the fixes for the major bugs that are in the last official release.

**Comment by drewwills** [comment]
@phillips1021 I totally agree.  This change should also be merged into rel-4-3-patches, and a 4.3.1 should be cut.

**Comment by bjagg** [comment]
I can take of the merge and release tomorrow

**Comment by drewwills** [comment]
@bjagg I would love it if you can take on a 4.3.1 release.

**Comment by drewwills** [comment]
Merged out-of-band;  thanks @bjagg!

**Pull request closed without merging**
