### PR TITLE
Removed duplicate maven-publish apply

### PR DESCRIPTION
**Pull request by JoshBrudnak**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [ ] tests are included
-   [ ] documentation is changed or added
-   [ ] [message properties][] have been updated with new phrases
-   [ ] view conforms with [WCAG 2.0 AA][]

##### Description of change

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Theres something strange going on with the OpenJDK 8 build.
https://travis-ci.org/Jasig/uPortal/jobs/336636125
It has been restarted several times now and it continues to fail without printing an error.
Testing locally to see if this is a regression in Travis CI or in Gradle.

**Comment by JoshBrudnak** [comment]
:confused: , I tested it locally with openjdk 8 and it worked fine.

**Comment by ChristianMurphy** [comment]
Yep :confused: 
I'm seeing OpenJDK working fine locally as well. :+1: 
I suspect this is an issue with Travis CI itself, possibly related to the recent outage.

**Comment by ChristianMurphy** [comment]
backported to `rel-5-0-patches` as 2d796098737b8b1ea391f7cf6375e4d5e915da74

**Pull request merged**
