### PR TITLE
fix(#1322): Resolve portlet import errors caused by Hibernate mappings when using uPortal 5 with Oracle 12

### LINKED ISSUE #1322: Using uPortal 5 with Oracle 12 causes import errors related to PREF_NAME & PREF_VALUE in PortletPreferenceImpl
**Describe the bug**
When initialising uPortal 5 against an Oracle 12 database, fragment layout import fails with "java.sql.SQLException: Stream has already been closed" in org.apereo.portal.portlet.dao.jpa.PortletDefinitionImpl.

This was discussed [on the uportal-user list](https://groups.google.com/a/apereo.org/forum/#!topic/uportal-user/j1Opk6Knv_k).  It was found that columns PREF_NAME & PREF_VALUE in PortletPreferenceImpl were causing the problem because they were being created as LONG in Oracle due to a default mapping in the version of Hibernate that uPortal is using.  

Originally this problem was raised as an issue #1217 and fixed in pull request #1218, but the change to force the PREF_NAME and PREF_VALUE columns to CLOB was not compatible with all databases.

Longer-term, the Hibernate version used by uPortal should be updated to one that correctly handles Oracle 12 mappings, but this is a wider ranging change.  We need a fix in the meantime.  

I have a local solution that is working which I'll submit in a pull request for review.

**To Reproduce**
Run portalInit in uPortal 5.3 using an Oracle 12 database.

**Expected behavior**
Import of fragment layouts is successful and does not result in errors.  The initialisation completes successfully. 

**Stacktrace**
See [stacktrace on forum question](https://groups.google.com/a/apereo.org/forum/#!topic/uportal-user/j1Opk6Knv_k)

**Platform:**
 - uPortal Version: uPortal 5.3
 - DB: Oracle 12

### PR DESCRIPTION
**Pull request by mairi**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

Resolves #1322 

This change introduces a workaround for an issue with Hibernate mappings for long strings when using Oracle 12.  Ultimately uPortal should move to a newer version of Hibernate, but in the meantime, adding a custom dialect to work with Oracle 12 is working for us locally.

I have looked at whether this could be made more generic for use with portlets but don't understand the structures well enough to know the best way to achieve that.  Suggestions for improvement very welcome!  I'm also unsure how this will behave with existing schemas - not easy to test this here.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by mairi** [comment]
Forgot local enforcement of the style guidelines before pushing changes - will need to pick this up tomorrow!

**Comment by ChristianMurphy** [comment]
```
./gradlew goJF
```

will do the trick.

**Comment by drewwills** [comment]
Thanks immensely @mairi!
@bjagg -- you  are pretty close to this topic... can you chime in?

**Comment by mairi** [comment]
Thanks @ChristianMurphy that goJF did the trick!  Noted for future ref :-)

**Comment by ChristianMurphy** [comment]
Barring any objects, I plan to merge this tomorrow.
/cc @bjagg @drewwills

**Pull request merged**
