### PR TITLE
WIP: rm layout.json v1

### PR DESCRIPTION
**Pull request by apetro**
+ Removes `/api/v1/dlm/layout.json`, which was [NPE-ing][NPE stacktrace] in vanilla `master` for me.
+ Adds stub documentation for the `/api/v4-3/dlm/layout.json` that presumably one uses instead when finding that the v1 web service is gone.

Removing a web service API is a big, breaking change -- but then uPortal 4->5 is a big, breaking-changes release.

cf. [uportal-dev@ list thread][]

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] documentation is changed or added

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement

[NPE stacktrace]: https://gist.github.com/apetro/5a150d589a4de1a0596f03c888ec42c6
[uportal-dev@ list thread]: https://groups.google.com/a/apereo.org/d/topic/uportal-dev/xsuqjBZO5V4/discussion

### CODE REVIEW

**Comment by asgrant** [comment]
This change will cause issues for uMobile app clients from OU. I was told by @bpowell that using the layout v4-3 is not technically possible. Brandon will need to voice his concerns and help with technical direction moving forward on this change and what is needed to help support mobile app clients.

**Comment by bpowell** [comment]
I'm currently writing an email to respond back to that uportal-dev thread about this now.

**Comment by apetro** [comment]
Cool. Flagged as `WIP`. Prompting the soul-searching about how much we need to support layout.json v1 for how long is a great outcome for this PR; I fully expect this PR will end up closed un-merged.

**Comment by ChristianMurphy** [comment]
@apetro is the plan still to close this out?
Or was there an offline conversation that found a way forward for this PR?

**Comment by ChristianMurphy** [comment]
Closing PR for now, it can be re-opened if a path forward is found.

**Pull request closed without merging**
