### PR TITLE
Issue #1438:  Support session-less access to uPortal REST APIs based …

### LINKED ISSUE #1438: Support session-less access to uPortal REST APIs based on the Authorization header (OIDC Id token)
## Summary

uPortal 5.1 and above provides a `/userinfo` endpoint through which content objects may obtain an OAuth2/OIDC Id token from the portal.  This token provides the identity, attributes, and group affiliations of the user, and it may be used to secure REST APIs.

The portal's own REST APIs, however, do not support this token.  Currently there is no way to invoke the portal's APIs except by presenting a `JSESSIONID` cookie representing an authenticated browser session.

We need to change that -- we need to provide support for other types of clients (besides JavaScript running on the portal page) to access these APIs as an authenticated user.  We need to support session-less access to uPortal REST APIs based on the portal-provided OIDC Id token in the Authorization header.

### PR DESCRIPTION
**Pull request by drewwills**
…on the Authorization header (OIDC Id token)

Resolves #1438 

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

See issue ticket.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
@jonathanmtran @mrapczynski

**Comment by jonathanmtran** [comment]
Initial quick testing against `api/groups` and `api/v4-3/dlm/portletRegistry.json` using `curl` look good. I will do additional testing and update as that progresses.

**Comment by drewwills** [comment]
Initial quick testing against api/groups and api/v4-3/dlm/portletRegistry.json using curl look good.

I'm glad you're using `curl`.

This solution has one annoying limitation...

If -- together with the `Bearer` token -- you also present a `JSESSIONID` cookie for a valid session (even a _guest_ session), the `Bearer` token will be ignored.

**Comment by jonathanmtran** [comment]
Taking a closer look, hitting `api/groups` with a OIDC token for the `student` user yields the following

```json
{
   "groups":[
      {
         "entityType":"group",
         "id":"pags.All Users (PAGS)",
         "name":"All Users (PAGS)",
         "creatorId":null,
         "description":"All Portal Users",
         "principal":{
            "key":"pags.All Users (PAGS)",
            "name":"12.pags.All Users (PAGS)"
         },
         "children":[

         ],
         "childrenInitialized":false
      },
      {
         "entityType":"group",
         "id":"pags.Desktop Device Access",
         "name":"Desktop Device Access",
         "creatorId":null,
         "description":"User Access by a non-mobile device (desktop)",
         "principal":{
            "key":"pags.Desktop Device Access",
            "name":"12.pags.Desktop Device Access"
         },
         "children":[

         ],
         "childrenInitialized":false
      },
      {
         "entityType":"group",
         "id":"local.13",
         "name":"Guests",
         "creatorId":"system",
         "description":"Unauthenticated users",
         "principal":{
            "key":"local.13",
            "name":"12.local.13"
         },
         "children":[

         ],
         "childrenInitialized":false
      },
      {
         "entityType":"group",
         "id":"pags.Respondr Theme Users",
         "name":"Respondr Theme Users",
         "creatorId":null,
         "description":"User Access by Theme",
         "principal":{
            "key":"pags.Respondr Theme Users",
            "name":"12.pags.Respondr Theme Users"
         },
         "children":[

         ],
         "childrenInitialized":false
      }
   ]
}
```

While the User Admin. portlet shows that `student` is in the following groups

* All Users (PAGS)
* Authenticated Users
* Desktop Device Access
* Everyone
* PAGS Root
* Respondr Theme Users
* Students

`api/v4-3/dlm/portletRegistry.json` appears to behaving as expected when fed a OIDC token.

**Comment by drewwills** [comment]
Thanks for posting this info @jonathanmtran -- I'll try to have a look at that next week.

**Comment by drewwills** [comment]
@jonathanmtran 

First attempt (`/uPortal/api/groups` with the `student` user), I get this data:

```
{
  "groups": [
    {
      "entityType": "group",
      "id": "pags.Respondr Theme Users",
      "name": "Respondr Theme Users",
      "creatorId": null,
      "description": "User Access by Theme",
      "principal": {
        "key": "pags.Respondr Theme Users",
        "name": "12.pags.Respondr Theme Users"
      },
      "children": [
        
      ],
      "childrenInitialized": false
    },
    {
      "entityType": "group",
      "id": "pags.Authenticated Users",
      "name": "Authenticated Users",
      "creatorId": null,
      "description": "All Authenticated Portal Users",
      "principal": {
        "key": "pags.Authenticated Users",
        "name": "12.pags.Authenticated Users"
      },
      "children": [
        
      ],
      "childrenInitialized": false
    },
    {
      "entityType": "group",
      "id": "pags.Desktop Device Access",
      "name": "Desktop Device Access",
      "creatorId": null,
      "description": "User Access by a non-mobile device (desktop)",
      "principal": {
        "key": "pags.Desktop Device Access",
        "name": "12.pags.Desktop Device Access"
      },
      "children": [
        
      ],
      "childrenInitialized": false
    },
    {
      "entityType": "group",
      "id": "pags.All Users (PAGS)",
      "name": "All Users (PAGS)",
      "creatorId": null,
      "description": "All Portal Users",
      "principal": {
        "key": "pags.All Users (PAGS)",
        "name": "12.pags.All Users (PAGS)"
      },
      "children": [
        
      ],
      "childrenInitialized": false
    },
    {
      "entityType": "group",
      "id": "local.33",
      "name": "Students",
      "creatorId": "system",
      "description": "All students",
      "principal": {
        "key": "local.33",
        "name": "12.local.33"
      },
      "children": [
        
      ],
      "childrenInitialized": false
    }
  ]
}
```

**Comment by drewwills** [comment]
@jonathanmtran -- Probably we should just get on a Zoom and try it together.

How old is your token?  (They expire in 3 minutes, typically.)

**Comment by jonathanmtran** [comment]
With 6a84c02, `/api/groups` and `/api/v4-3/dlm/portletRegistry.json` are returning the user-specific results as expected.

**Pull request merged**
