### PR TITLE
UP-4742: Use AlternativeMaximizedLink into sitemap - master

### PR DESCRIPTION
**Pull request by jgribonvald**
Set anchor url with Alternative Maximized Link on sitemap

PR for master

### CODE REVIEW

**Comment by bjagg** [comment]
@jgribonvald Have you signed up at https://issues.jasig.org/ ?

**Comment by cousquer** [comment]
@bjagg answering for @jgribonvald (he is on hollidays, and take a rest with his family) : yes
[https://issues.jasig.org/browse/UP-4742](https://issues.jasig.org/browse/UP-4742)

**Comment by bjagg** [comment]
Thanks @cousquer! I was able to grant him rights as a developer.

**Comment by cousquer** [comment]
you can do it and do it for me too...

**Pull request merged**
