### PR TITLE
UP-4425 Marketplace search returned portlets user doesn't have access to

### PR DESCRIPTION
**Pull request by jameswennmacher**
https://issues.jasig.org/browse/UP-4425

See screenshot in issue of problem.  Results now match Portlet Registry search.

### CODE REVIEW

**Comment by jameswennmacher** [comment]
I don't believe this change negatively impacts UW Madison which uses Marketplace extensively, but flagging a note to encourage review.

**Comment by jameswennmacher** [comment]
Merging due to high confidence will not impact UW Madison in some unexpected way.

**Comment by gcarroll** [comment]
Hi James,

I have a quick question.  What exactly is the marketplace portlet?  I know going through the uPortal properties I saw a naming option for this portlet.  I may have a use for this portlet if this is useful in a e-commerce or online sales case senario.

Thanks,

Geordie Carroll

**Comment by timlevett** [comment]
Seems fine to me @jameswennmacher

**Comment by jameswennmacher** [comment]
Marketplace attempts to create an app-store like approach to promoting 
the portlets available to users.  Basically it adds additional meta data 
and images to provide more of an app-store look.  There is also a rating 
system, though it is not fully developed (you can rate and comment on a 
portlet, but you can't see other's ratings yet or get a computed average 
of ratings for a portlet).

James Wennmacher - Unicon
480.558.2420

**Pull request merged**
