### PR TITLE
UP-4729 : Activating flyout menu option from portal.properties

### PR DESCRIPTION
**Pull request by jgribonvald**
Usefull to avoid to modify the option in the xsl.

### CODE REVIEW

**Comment by drewwills** [comment]
### General Note on New Pull Requests

Please hold off on merging pull requests to `master` for a brief period.  A significant refactor is already underway for uPortal 5, and the potential for difficult conflicts is large.  I'll do my best to make this change happen quickly.  Thank you for your patience.

**Comment by cousquer** [comment]
@jgribonvald 
This is a blast! You save my time... thanks Julien

**Comment by jgribonvald** [comment]
Ok Drew I will wait the new version for new PR.

But it would be great if this one could be integrated in 4.3.x branch.

**Comment by jgribonvald** [comment]
Just to explain why I didn't rebased

I need to know  if PR #681 will be integrated into 4.3 or 4.4, in this case this PR can be merged without problems. And if not I will do a rebase to be on HEAD of the master.

**Comment by drewwills** [comment]
Merged out-of-band to both `master` and `rel-4-3-patches`.

**Pull request closed without merging**
