### PR TITLE
Cors post null content type

### PR DESCRIPTION
**Pull request by bpowell**
##### Checklist
-   [ x ] the [individual contributor license agreement][] is signed

##### Description of change
If a 'POST' request comes in with a null content-type, default it to `CORSRequestType.ACTUAL`

### CODE REVIEW

**Comment by bpowell** [comment]
@bjagg this fixes the actionURL problem that we have been discussing on the dev list.

**Comment by ChristianMurphy** [comment]
alternative to #1043

**Comment by bpowell** [comment]
@ChristianMurphy not an alternative, this should really be in addition to #1043

**Comment by bjagg** [comment]
:+1:

**Pull request merged**
