### PR TITLE
UP-4434 Create new mobile icons for portlets

### PR DESCRIPTION
**Pull request by rrglomsk**
I created these icons for Oakland University's fork of uPortal, and am contributing them back to the project so that others may use them at community request.
These are the 72x72 portlet icons geared for mobile, and there is possibility of adding the 32x32 versions for portlet definitions later, if there is a designated directory to put them in.

Examples:
calendar_alt email weather_alt advising

https://issues.jasig.org/browse/UP-4434

### CODE REVIEW

**Comment by drewwills** [comment]
@rrglomsk -- Have you filed an ICLA with Apereo yet?  https://www.apereo.org/sites/default/files/licensing/apereo-icla.pdf

These icons look great -- is there someone who can use these icons to add mobilIconUrl parameters (where reasonably appropriate) to portlet-definition.xml files that don't currently have them?

Can we get the 32x32 versions?

**Comment by rrglomsk** [comment]
@drewwills I just filed one and received a confirmation, thanks!

I would be more than happy to commit the 32x32 icons, I just need to know where they should be placed in the directory structure. I was thinking either in the "uPortal/uportal-war/src/main/webapp/media/skins/icons" directory, or making a new folder within that since that's where the mobile icons folder is?

**Comment by rrglomsk** [comment]
I went ahead and added the 32x32 versions of the icons to the icons directory, hopefully that works out fine! They should be good to go :)

**Comment by timlevett** [comment]
:+1:  cool.

**Comment by jameswennmacher** [comment]
This is fantastic.  The icons look great.  Per Drew's suggestion on 4/22, I created issue https://issues.jasig.org/browse/UP-4467 to track that idea.  Since the ICLA is in, I'll go ahead and merge these icons in so people can start to make use of them.

**Comment by asgrant** [comment]
@jameswennmacher I'll see if we can complete UP-4467, @rrglomsk is no longer with us, so I'll have another person work on this.

**Pull request merged**
