### PR TITLE
UP-4731: Update dependency versions (rel-4-3-patches backport)

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

PRs #837, #844, and #851 cherry-picked for rel-4-3-patches.
See description in ticket [UP-4731](https://issues.jasig.org/browse/UP-4731).

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
LGTM :+1: 

Did you run a `$ ant clean initportal` with these changes, start tomcat, and click around a bit?

**Comment by ChristianMurphy** [comment]
@drewwills I've check that it compiles, I have not smoke tested this yet.

**Comment by drewwills** [comment]
Testing locally...

error

**Comment by drewwills** [comment]
@ChristianMurphy -- I un-did the version updates that were causing regressions:  https://github.com/Jasig/uPortal/pull/900/commits/98ee0982f539246414de17ea8798d0655ecef661

We should discuss tomorrow whether we are satisfied without those changes, or if we should really resume this work and do the difficult things it will take to update those libraries as well.

**Comment by ChristianMurphy** [comment]
👍 Upgrading commons and groovy are worth while on their own.

**Pull request merged**
