### PR TITLE
Logo centered in mobile view only, search bar location changed

### PR DESCRIPTION
**Pull request by dmartign**
Issue UP-4476

### CODE REVIEW

**Comment by vertein** [comment]
Cool.  What did it look like before?

**Comment by dmartign** [comment]
Both things were not centered on mobile view.

**Comment by timlevett** [comment]
:+1:

**Comment by drewwills** [comment]
I'm reviewing the present state of these items in master.  The search bar is centered and looks good;  would you (any of you) say centering the logo is an obvious/community choice or an implementation decision?

**Comment by drewwills** [comment]
Closing this PR -- as well as the associated JIRA -- as a stylistic/implementation detail.

**Pull request closed without merging**
