### PR TITLE
Allow the main navigation hamburger menu to be used (in lieu of tabs) on any size display -- xs, sm, md, lg, or all of them

### PR DESCRIPTION
**Pull request by drewwills**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

This enhancement allows portal adopters to specify a property -- `org.apereo.portal.layout.useTabsSize` -- that determines at what display size (and above) the main navigation hamburger menu will switch to tabs.  Before this change, the menu is always hamburger at or below `@screen-sm-max` and always tabs at `@screen-sm-min` or above.

The options (for this property) are:

  - sm
  - md
  - lg
  - none

If `none` is specified, the main navigation menu will always be hamburger style.

The property is optional;  the default behavior is the same as before the change.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
@cousquer -- it looks like at one time you wanted to refactor the `navigation.less` file.

**Comment by drewwills** [comment]
This PR includes a tiny but important fix to the `OidcUserInfoController`, so I'm going to merge it slightly sooner than I normally would.

**Comment by cousquer** [comment]
Hello @drewwills [post merged comment - apologies for the delay,]
Drew,
Due to -well, [you know and can imagine my context, Time Zone, etc.]... (I've been also working on uPortal Summit Paris Feedback Document in English the all day.)
**This PR should fix a lot of my three years ago imperfect code. As usual, Many thanks.**
_I will take time one hour tomorrow to test this PR. and will send you feedbacks._

**Comment by cousquer** [comment]
A simple comment. this is a massive visual, logical and end user Experience change.
My only Request may be that this should be communicate to the community as one of the two first idems (in strong, bold) in the changelog.
/cc @ChristianMurphy @drewwills @jgribonvald

**Comment by drewwills** [comment]
@cousquer -- Covering this new capability in the change logs is a great idea.

The default behavior of navigation in Respondr is unchanged by this PR.

**Pull request merged**
