### PR TITLE
UP-4782: Fix .search-dropdown class styling in entity-selector.less

### PR DESCRIPTION
**Pull request by CR96**
##### Checklist

-   [x] the [individual contributor license agreement] is signed
-   [x] commit message follows [commit guidelines]

##### Description of change

https://issues.jasig.org/browse/UP-4782

Search results no longer occupy the same space as the categories list.

#### Before fix
Before fix

#### After fix
After fix

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@CR96 does #795 resolve the issue you are seeing? Also what browser are you seeing the issue on?

**Comment by cousquer** [comment]
@CR96 @ChristianMurphy 
This is really strange, :flushed: I can not reproduce the bug in uP4.4-snapshot in Win FF latest, Chrome Latest, Edge Latest, internet explorer 11 latest. on my dev env. with defaultSkin the search result are under the form field ( where "uPortal" is written) on the right. and I don't have the z-index-like display issue (see in google: "browser stacking context" on MDN).

@CR96 from the screenshot "Before fix": it seems that you may have perhaps (perhaps...) a conflict of uPortal default skin css and your custom skin css, :confused:

Could you tell us please : 

- if  you have a customSkin ?
- what version of uPortal are you running uPortal 4.3.0 ? 4.3.1?
- on what OS, what browser (+browser's version), do you experience this strange bug?

**Comment by CR96** [comment]
@ChristianMurphy @cousquer We do have a customSkin. I replaced the entity-selector css in our project with the css from base uPortal and it made the overlay functional (ignoring its appearance), so it does seem to be a css conflict on our side somehow - sorry about that. For reference, we're running uPortal 4.3.1 and experienced the bug on the latest Firefox and Chrome under Linux Mint 18. 

@ChristianMurphy Strangely, merging in the changes from #795 actually introduces the top-level redirect bug into our groups admin portlet which wasn't previously an issue in our build. It worked correctly when I tried it with base uPortal, so it's likely something on our end - I'll let you know if I figure out what's happening.

**Comment by ChristianMurphy** [comment]
> Strangely, merging in the changes from #795 actually introduces the top-level redirect bug into our groups admin portlet which wasn't previously an issue in our build. It worked correctly when I tried it with base uPortal, so it's likely something on our end - I'll let you know if I figure out what's happening.

If you are running off uPortal 4.3.1 #794 would be safer to test with.
Merging #795 would bring all the [semver major](http://semver.org/) changes in uPortal 5 along with it.

**Comment by cousquer** [comment]
@CR96 Thanks, I'll try to reproduce the bug tomorrow (Paris - France local time) on a 
Centos 7 -> FF 45.4.0
IOS 10.2 (14C92) ->  FF 5.3 (2)

**Comment by CR96** [comment]
#794 merged more cleanly. No new issues this time after updating the two files in the pull request. The css issue still stands despite the merge, so it isn't related to the redirect issue. I'll keep playing with our css settings to figure out what might be causing it.

**Comment by cousquer** [comment]
@CR96 @ChristianMurphy Can't reproduce the issue in Linux Centos 7 FF 45.4.0

couldnt reproduce the issue in rel-4.3-patches and rel-4.4-snapshot

**Comment by CR96** [comment]
All right, looks like it's specific to our customSkin then. I'll go ahead and close this.

**Pull request closed without merging**
