### PR TITLE
UP-4961:  Changed org.jasig class to org.apereo, and fixed versioning

### PR DESCRIPTION
**Pull request by cbeach47**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [x] tests are included
-   [x] documentation is changed or added
-   [x] [message properties][] have been updated with new phrases
-   [x] view conforms with [WCAG 2.0 AA][]

##### Description of change
Resolves issue https://issues.jasig.org/browse/UP-4961 by switching the org.jasig class reference to org.apereo.

Also added a change so a local build of uPortal is built as 5.0.1-SNAPSHOT.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Hey @cbeach47, it looks like this change is causing a test to fail. :construction_worker_man: :no_entry: 
CI logs aren't providing many details.

```
Putting task artifact state for task ':autoLintGradle' into context took 0.0 secs.
Executing task ':autoLintGradle' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Download https://repo1.maven.org/maven2/com/google/code/findbugs/findbugs/3.0.1/findbugs-3.0.1.pom
Download https://repo1.maven.org/maven2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jFormatString/2.0.1/jFormatString-2.0.1.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.2/asm-debug-all-5.0.2.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.2/asm-parent-5.0.2.pom
Found locally available resource with matching checksum: [https://repo1.maven.org/maven2/org/ow2/ow2/1.3/ow2-1.3.pom, C:\Users\appveyor\.gradle\caches\modules-2\files-2.1\org.ow2\ow2\1.3\f679d6639bfb209b0836a5e7cf09bfbcc1a41f06\ow2-1.3.pom]
Download https://repo1.maven.org/maven2/com/apple/AppleJavaExtensions/1.4/AppleJavaExtensions-1.4.pom
Download https://repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/bcel-findbugs/6.0/bcel-findbugs-6.0.pom
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.2/asm-5.0.2.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.ant/0.7.8/org.jacoco.ant-0.7.8.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/0.7.8/org.jacoco.core-0.7.8.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.report/0.7.8/org.jacoco.report-0.7.8.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.1/asm-debug-all-5.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
:autoLintGradle (Thread[Daemon worker,5,main]) completed. Took 18.929 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':uPortal-webapp:test'.
> There were failing tests. See the report at: file:///C:/projects/uportal/uPortal-webapp/build/reports/tests/test/index.html
```
https://ci.appveyor.com/project/drewwills/uportal/build/1.0.853#L18763

**Comment by ChristianMurphy** [comment]
:recycle: :building_construction: Closing and re-opening PR to restart AppVeyor.

**Comment by cbeach47** [comment]
Please hold off merging this - I am looking into a test scenario that's not behaving.

**Comment by drewwills** [comment]
Looks good.  👍

**Comment by cbeach47** [comment]
Discussed with Benito and decided this can be merged and we'll handle the failing test scenario (user reset layout doesn't reset the column layouts) in a separate PR.

**Pull request merged**
