### PR TITLE
Changed jasig link to apereo on error page.

### PR DESCRIPTION
**Pull request by MichaelFrieze**

### CODE REVIEW

**Comment by drewwills** [comment]
@MichaelFrieze -- Thanks for this contribution.  Seems like a no-brainer.  Are you willing to submit an ICLA?  https://www.apereo.org/licensing/agreements

**Comment by asgrant** [comment]
@drewwills I believe that Mike submitted an ICLA via FAX a while ago. So he should be set, unless it wasn't received.

**Comment by drewwills** [comment]
@asgrant and @MichaelFrieze -- I don't see Michael's name in the ICLA column here:  http://licensing.apereo.org/

I do, however, see Oakland's institutional agreement.

@apetro Do you know if that covers it?  Does anyone know of a reason we're not seeing it?

**Comment by drewwills** [comment]
This omission was covered in the fix for UP-4718.

**Pull request closed without merging**
