### PR TITLE
UP-4710: Bug on GuestUserTester

### PR DESCRIPTION
**Pull request by jgribonvald**
see on JIRA for more details : https://issues.jasig.org/browse/UP-4710

### CODE REVIEW

**Comment by jgribonvald** [comment]
use the test without the class update and you will see the problem

**Comment by jgribonvald** [comment]
Now there are problems on guest evaluation. There is something but it would be great to know what, do you know why the pags was done on this way ?

**Comment by drewwills** [comment]
@jgribonvald -- For starters... thank you so much!

This is excellent work.  Accurate diagnosis of the issue, correct solution, JIRA, test cases, and a pull request... this contribution is essentially perfect.  You're exactly the sort of person we want involved.  Please, more of these.

**Comment by jgribonvald** [comment]
@drewwills : :blush:
With an easy correction it was the least that I could do

**Pull request merged**
